# Generated by Django 5.2.1 on 2025-05-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField()),
                ("author", models.CharField()),
                ("genre", models.CharField()),
                ("date_of_birth", models.DateField()),
                ("description", models.TextField()),
                ("price", models.FloatField()),
                ("rating", models.FloatField()),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
    ]
