name: Docker Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
      DATABASE_URL: postgres://user:pass@localhost:5432/db

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker backend
      run: docker build -t test-backend ./backend

    - name: Build Docker frontend
      run: docker build -t test-frontend ./frontend

    - name: Start Docker Compose (without detached mode)
      run: docker compose up -d

    - name: Wait for services to be healthy
      run: sleep 15

    - name: Run backend healthcheck
      run: curl --fail http://localhost:8000/api/ || exit 1

    - name: Run frontend healthcheck
      run: curl --fail http://localhost:3000 || exit 1

    - name: Stop containers
      run: docker compose down