# Generated by Django 5.2.1 on 2025-05-28 16:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_genre_remove_books_author_alter_books_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='date_of_birth',
        ),
        migrations.AlterField(
            model_name='books',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
